### ISSUE TITLE
Personal information in downloaded .ass format subtitles

### ISSUE THREAD

**Issue by xXxBobDolexXx** [Godzil/Crunchy#98] opened 2018-10-28 20:02 UTC
**Describe the bug**
When opening .ass subtitles in notepad, it shows the account the subtitles were downloaded with
.srt subtitles do not have this problem.

Not sure how difficult it is to implement but a solution could be to remove line 2 from the .ass files before merging.

**Expected behavior**
no personally identifying information in the downloaded files.
**Screenshots**
http://images2.imagebam.com/4f/4e/7a/611b3d1012998084.PNG
**Please fill theses informations:**
(Add a X between brackets to make them ticked if relevant)
 - OS: [e.g:. Windows 10, Mac OS X 10.13, ...]
 - [X] I'm using the latest version of Crunchy
 - [X] I have a premium accrount on CR
 - [ ] I am using a VPN
 - My region in the world (country or continent): Canada
 - Series you get a problem with (and specify which episode if it is specific to one): Noticed it on Goblin Slayer
 - The command line you are running Crunchy with: crunchy -u username -p password -n "{SERIES_TITLE} Episode {EPISODE_NUMBER} - {EPISODE_TITLE}" https://www.crunchyroll.com/goblin-slayer
 - The message Crunchy is giving you, if any:

**Please be careful to remove your real account login and password if they appear!**

**Additional context**

_Also don't hesitate to add labels you feel apropriate on your report._
_Please don't edit logs if you are adding them, apart from removing sensitive informations like login/password_

**Comment by Godzil** [comment] 2018-11-24 15:53
What is the problem with that? 

Apart if you are sharing the file illegally, I don’t see the point.

So no sorry no plan do do such a thing. This app try to be as clean as possible, nhave to be use as close as possible to fair rights, and sharing the downloaded files are not part of that.

So give me a good reason which is NOT sharing, and I may consider.

Up so far I’m closing this as not a bug.

**Closed by Godzil** 2018-11-24 15:53 UTC
