### ISSUE TITLE
Doesn't filter out invalid filename characters

### ISSUE THREAD

**Issue by Californ1a** [Godzil/Crunchy#47] opened 2017-09-09 23:21 UTC
When using -n to create a naming scheme, if you include the {EPISODE_TITLE} and the episode title includes an invalid character, for example, a question mark, then it won't download the episode. It should instead just remove the question mark from the filename.
![](https://i.imgur.com/NJeoc60.png)

**Comment by Godzil** [comment] 2017-11-18 12:00
Duplicate of #26

**Closed by Godzil** 2017-11-18 12:00 UTC
