### ISSUE TITLE
Download specific episode

### ISSUE THREAD

**Issue by Jfigs101** [Godzil/Crunchy#4] opened 2016-08-23 15:20 UTC
Wondering if there is a way to download a specific episode using the episode URL. Please close if not possible.

**Comment by Godzil** [comment] 2016-08-23 20:46
No as far as I know it's not possible, but I will not close it for a simple reason, that an option that should be there!

**Comment by Jfigs101** [comment] 2016-08-23 22:20
So I found this project that encountered the same issue with HSL, but before that issue, it accepted a Crunchyroll URL and would download that episode. Might be worth taking a look at: https://github.com/einstein95/crunchy-xml-decoder

**Comment by Godzil** [comment] 2016-08-24 07:43
Thanks for that project, I wil take a look, I think there are a few interesting part, especially for the subtitles which is one other big issue for me with current version of crunchy

**Comment by PrestonCook** [comment] 2016-09-05 00:15
On the Deathspike version there were some comments about fixing the episode filter by changing line 96 of the series.js file from:

`episode: parseInt(episode[0], 10),`

to:

`episode: parseInt(episode[1], 10),`

Then you would be able to actually select a particular episode by adding `-e <some number>` to the command like it was intended. I've noticed that it's off by one. So if you want to download episode 21 you need to say `-e 20`.

I would definitely push for the URL option, though. Using the URL of the video directly would be a lot cleaner in my mind. Some Anime have specials/movies so how are they numbered (see One Piece for example)? There are also a number of episodes on Crunchyroll that have episode numbers like 7.5 or 13.5. How would those be numbered and would they offset the next episodes? For example would Episodes 7, 7.5, and 8 be indexed like 7, 8, 9?

I definitely like the batch downloading functionality, but the URL option would be a lot cleaner.

**Comment by Godzil** [comment] 2016-09-05 15:42
That's a good idea to clearly add support for full episode URL.

For 7.5, 10.5 etc. My (future) change take care of them. It does not support all of the extra episodes, but most of them

In fact I'm thinking about a major change in how episodes are listed and saved for batch. Will see lots of things are still in progress.

**Closed** 2017-02-13 00:53 UTC
Labels: enhancement
