### ISSUE TITLE
Problem with the IP

### ISSUE THREAD

**Issue by skthanu** [Godzil/Crunchy#54] opened 2017-11-24 04:03 UTC
Hello there, I have premium account, but Crunchy block some anime from my country, I mean, it is availble on Crunchy but i can not watch from my country, however if I use zenmate to fake IP to USA, i can watch it but I am still can not download by using crunchy
Can you please tell me how can I still download it?
This is how it say: 
![image](https://user-images.githubusercontent.com/33084800/33195091-32c87122-d107-11e7-8ca9-d067cdab81df.png)
And this is the link: `http://www.crunchyroll.com/my-hero-academia`

**Comment by clienthax** [comment] 2017-11-25 21:03
dupe of https://github.com/Godzil/Crunchy/issues/41

**Comment by Godzil** [comment] 2017-11-26 08:38
ZenMate is supposed to be a VPN, are you using it as an external app or a plugin in a browser?

If it is as an app, it should work as the VPN redirect all of your computer traffic. If it is as a browser plugin it will make only the browser to use the VPN. 
So I would recommend you to download the "ZenMate for Windows" version if is it not the version you are currently using: https://zenmate.com/products/vpn-for-windows/

**Comment by Godzil** [comment] 2018-02-27 13:52
Closing as it is not a Crunchy issue

**Closed by Godzil** 2018-02-27 13:52 UTC
