### ISSUE TITLE
Merged season issue

### ISSUE THREAD

**Issue by clienthax** [Godzil/Crunchy#50] opened 2017-10-27 23:05 UTC
Seems attempting to download this http://www.crunchyroll.com/the-ancient-magus-bride
Will cause both 'seasons' to be downloaded as S1 with -1 -2 -3 appended on the end of the filenames.

**Comment by Godzil** [comment] 2017-11-05 16:27
See #51, this is mainly CR fault to not properly tag seasons (and in this case to have put OAV and the anime in the same part)

**Comment by Godzil** [comment] 2017-11-18 12:01
Duplicate of #51

**Closed by Godzil** 2017-11-18 12:01 UTC
Labels: duplicate
